### PR TITLE
WL-4072 Having the calendar class to add/sub the number of months to current date

### PR DESCRIPTION
**Pull request by surya-janani**
toMonthsInput variable reads number of display months in future range and fromMonthsInput var reads number of months required from the past from configurable property.

### CODE REVIEW

**Comment by buckett** [comment]
For contributing back to Sakai you should also document your properties in `default.sakai.properties` in the config package. You should also follow the pattern that is used for existing calendar properties, something like `calendar.export.previous.months` and `calendar.export.next.months` are more in keeping with the existing properties and more humanly readable.

**Comment by surya-janani** [comment]
Not sure if we want the word export in the property name, as this property could be used for features other than exporting iCal.  Is calendar.timerange.previous.months any good? or ical.timerange.previous.months

**Comment by buckett** [comment]
Such as?

**Comment by buckett** [comment]
> Not sure if we want the word export in the property name, as this property
> could be used for features other than exporting iCal. Is
> calendar.timerange.previous.months any good? or
> ical.timerange.previous.months

Such as?

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by surya-janani** [comment]
I don't see it being used anywhere else currently. Was just thinking for future may be when they want to merge internal calendars in particular range or something new like printing events in a range.
It just feels like a more generic property. Even the method is named as getICalTimeRange and not something like generateExportTimeRange()  .

**Comment by buckett** [comment]
iCal is only used for export/import.

**Comment by surya-janani** [comment]
Closing as I made some mistake creating WL-4072 branch .

**Pull request closed without merging**
